# Generated by Django 4.2.2 on 2023-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
