# Generated by Django 4.2.2 on 2023-06-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_book_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
