# Generated by Django 4.2.2 on 2023-06-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
