# Generated by Django 4.2.2 on 2023-06-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chaper_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.CharField(max_length=20)),
                ('chapter_name', models.CharField(max_length=100)),
                ('chapter_href', models.CharField(max_length=100)),
            ],
        ),
    ]
