# Generated by Django 4.2.2 on 2023-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0002_remove_chapter_chaper_id_chapter_chapter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='id',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_no',
            field=models.IntegerField(default=0),
        ),
    ]
