# Generated by Django 4.2.2 on 2023-06-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_id'),
        ('user', '0002_rename_user_name_user_username'),
    ]

    operations = [
    ]
